#! /usr/bin/python3

# Copyright 2023 SUSE LLC
#
# This file is part of instance-billing-type-check
#
# instance-billing-type-check is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# instance-billing-type-check is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# instance-billing-type-check. If not, see <http://www.gnu.org/licenses/>.

import logging
from instance_check import frameworkfactory

# PROCESS
log = logging.getLogger('instance-billing-type-check')
# either metadata comes as a param
# or it needs to be fetched
# get params if not fetched
metadata = None  # frameworkfactory.get_metadata(log)

if metadata:
    try:
        instace_type = metadata.instance_type()
        log.info('Done.')
    except KeyError as err:
        log.error('Determining instance billing type failed: {}'.format(err))
else:
    log.warning('No instance metadata. Process finished.')
